### ISSUE TITLE
Fitur send message group dan sender dari group

### ISSUE THREAD

**Issue by fadli0207** [WhatsAppNETClient/WhatsAppNETAPINodeJs#1]
Sebelumnya keren banget ini. 
Saran/request ni, ditambahkan fitur untuk send message ke group juga baca pengirim/sender user yang kirim message ke group, saat ini yang muncul hanya nama groupnya. 

Terima kasih

**Comment by WhatsAppNETClient** [comment]
Terima kasih om atas masukannya, insyaAlloh bisa saya tambahkan di update berikutnya

**Comment by WhatsAppNETClient** [comment]
> Sebelumnya keren banget ini.
> Saran/request ni, ditambahkan fitur untuk send message ke group juga baca pengirim/sender user yang kirim message ke group, saat ini yang muncul hanya nama groupnya.
> 
> Terima kasih

@fadli0207 

Udah rilis om versi terbarunya, silahkan dicoba :-)
