### ISSUE TITLE
Fitur Sender Name Kontak Baru

### ISSUE THREAD

**Issue by satriax** [WhatsAppNETClient/WhatsAppNETAPINodeJs#2]
Apakah bisa ditambahkan nama pengirim dari kontak yang belum disimpan? 
Saat ini dapatnya cuma sender.Id
Baca2 di https://github.com/pedroslopez/whatsapp-web.js/issues/165 bisa pakai getContact.

Terima kasih mas

**Comment by WhatsAppNETClient** [comment]
Sepertinya bisa om, nanti saya cek lagi

**Comment by satriax** [comment]
Klo nomor yg sudah kesimpan bisa dapat nama. Yang belum kesimpan yg ga dapat, property name isinya empty string. 
Terima kasih om

**Comment by WhatsAppNETClient** [comment]
Udah saya tambahkan om @satriax, di versi terbaru, silahkan dicek
