### ISSUE TITLE
Welcome Message di Grup

### ISSUE THREAD

**Issue by satriax** [WhatsAppNETClient/WhatsAppNETAPINodeJs#3]
Halo mas,

Apakah ada event yg implementasikan https://docs.wwebjs.dev/Client.html#event:group_join ?
Rencananya mau saya buat bikin Welcome Message saat ada member baru join di grup.

Terima Kasih

**Comment by WhatsAppNETClient** [comment]
fiturnya udah saya tambahkan om @satriax, nunggu rilis berikutnya
