### ISSUE TITLE
[ASK] Authenticating via JSON session is not supported for MultiDevice-enabled

### ISSUE THREAD

**Issue by xxxmarkoxxx** [WhatsAppNETClient/WhatsAppNETAPINodeJs#4]
![image](https://user-images.githubusercontent.com/45991802/169785275-b072915e-68a6-46b6-a8c7-7d5e77d98f8f.png)

selamat sore.
om kalau error ot suport multidevice gini solvenya gimana ya?

**Comment by WhatsAppNETClient** [comment]
Cek issues yg [ini](https://github.com/WhatsAppNETClient/WhatsAppNETClient2/issues/23) om.
